import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import  Main from '../components/main'
import Servece from '@/components/Servece'
import About from '@/components/About'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <div>
      <Head>
        <title>Fidato agro plus-منصه متخصصه بمجال الزراعه</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Main/>
    <Servece/>
    <About/>


    </div>
  )
}
