import { Inter } from 'next/font/google'
import Main from '../Components/Main'
import Head from 'next/head'
import BestS from '@/Components/BestS'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
<div className=' bg-[#eee] '>
<Head>
<title>Lamsa_Candle</title>
<meta name="description"  content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="../img/logo.jpeg" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Kristi&family=Satisfy&family=Yesteryear&display=swap" rel="stylesheet" />


</Head>
<Main/>
<BestS/>

</div>
  )
}
